version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: ./go-clean-architecture/Dockerfile.dev
    volumes:
      - ./go-clean-architecture:/app
    environment:
      - PORT=8080
      - GO_ENV=development
      - DB_USER=root
      - DB_NAME=dev
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_MAXOPENCONNECTION=100
      - DB_MAXIDLECONNECTION=10
      - DB_CONNECTIONMAXLIFETIMEHOUR=1
      - TEST_DB_NAME=test
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_POOLSIZEPERCPU=10
      - REDIS_MINIDLECONNECTION=0
      - REDIS_POOLTIMEOUTSECONDS=4
      - ENGINE_URL=http://dialogue-processing-server:8080
      - AWS_S3BUCKETNAME=${AWS_S3BUCKETNAME}
    ports:
      - "3333:3333"
      - "6060:6060"
    entrypoint:
      - dockerize
      - -timeout
      - 30s
      - -wait
      - tcp://mysql:3306
      - -wait-retry-interval
      - 3s
    command: ["sh", "./entrypoint.sh"]
    depends_on:
      - mysql
      - redis
  redis:
    build:
      context: ./redis/docker
    ports:
      - "6379:6379"
  mysql:
    build:
      context: ./mysql/docker
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 30s
      retries: 10
volumes:
  mysql_db:
    driver: local
